spring.application.name=Enotes_API_Service

server.port=1212

spring.datasource.url=jdbc:mysql://localhost:3306/e_notes_db
spring.datasource.username=root
spring.datasource.password=Durgesh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


